<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $username
     * @throws NonUniqueResultException
     * @throws NoResultException
     * @return User
     */
    public function findOneByUsername(string $username): User
    {
        $query = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.username = :username')
            ->setParameters([
                'username' => $username,
            ])
            ->getQuery();

        return $query->getSingleResult();
    }
}
